import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`inter.className horizontal-center lg:max-w-4xl w-full mx-5 md:mx-10 lg:mx-auto p-2`}
      >
        {children}
      </body>
    </html>
  );
}
